apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.Common.ServiceName }}
  namespace: {{ .Values.Common.NameSpace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /service/$2
spec:
  ingressClassName: {{ .Values.Ingress.IngressClassName }}
  defaultBackend:
    service:
      name: service-{{ .Values.Common.ServiceName }}
      port:
        number: 80
  rules:
    - http:
        paths:
          - path: /service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: service-{{ .Values.Common.ServiceName }}
                port:
                  number: 80
